services:
  frontend:
    build:
      context: ./WeatherApp
      dockerfile: Dockerfile
    ports:
      - "3000:5173"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - BACKEND_CORS_ORIGINS=http://frontend:3000
          